use crate::infra::fs;

/// Generate init.sh. The shell function intercepts cover/uncover/auto and evals the output.
pub fn render_init(binary_path: &str) -> String {
    let home = fs::envswitch_home();

    format!(
        r##"# envSwitch shell integration
# Generated by: envswitch init

_ENVSWITCH_BIN="{}"
_ENVSWITCH_HOME="{}"

# Shell function: auto-eval for cover/uncover/auto (they output complete env scripts)
envswitch() {{
    case "$1" in
        cover|uncover|auto)
            eval "$("$_ENVSWITCH_BIN" "$@")"
            ;;
        *)
            "$_ENVSWITCH_BIN" "$@"
            ;;
    esac
}}

# Load global covers on startup
__envswitch_load_global() {{
    local sf="${{_ENVSWITCH_HOME}}/state/global.json"
    if [ -f "$sf" ] && command -v python3 >/dev/null 2>&1; then
        python3 -c "
import json
try:
    with open('$sf') as f:
        data = json.load(f)
    for c in data.get('covers', []):
        print(c.get('module_name','') + ':' + c.get('version',''))
except: pass
" 2>/dev/null | while IFS=: read -r mod ver; do
            [ -n "$mod" ] && eval "$("$_ENVSWITCH_BIN" cover "$mod" "$ver" --global 2>/dev/null)"
        done
    fi
}}

__envswitch_load_global
"##,
        binary_path,
        home.display(),
    )
}
